### ISSUE TITLE
submit bozuk spam testi açıklamada

### ISSUE THREAD

**Issue by omerumur14** [lyk2018-python/deductive-reasoning#33]
![ekran goruntusu - 2018-08-03 14-57-27](https://user-images.githubusercontent.com/33175840/43641776-985e51ae-972d-11e8-8060-9961750baf75.png)

**Comment by omerumur14** [comment]
<3<3<3<33<3<3<33<3<3<33<3<33<3<3<3<33<3

**Comment by mirkan1** [comment]
Repost 📄

**Comment by omerbselvi** [comment]
done
